import { TechnologiesList } from "../About/Blocks/specs/Technologies";

export type ProjectInterface = {
    slug: string;
    name: { ru: string; en: string };
    shortName: { ru: string; en: string };
    description: { ru: string; en: string };
    domain: string;
    rating: number;
    year: number;
    status: "developing" | "completed";
    participating: "team" | "selfown";
    devTimeMonths: number;
    gitHubLink?: string;
    technologies: TechnologiesList[];
    images: number;
    coverBrightmess?: "ligth" | "dark";
};

export type ProjectsType = typeof projects;

export type ProjectsList = ProjectsType[number & keyof ProjectsType]["slug"];

export function isProjectSlug(slug: string): slug is ProjectsList {
    return projects.some((p) => p.slug == slug);
}

export const projects = [
    //web
    {
        slug: "kvll",
        name: { en: "Krasnodar construction real estate portal", ru: "Портал строительной недвижимости Краснодара" },
        shortName: { en: "Real estate portal", ru: "Портал недвижимости" },
        description: {
            en: "A large project based on the Yii2 framework, developed by a team of three people. The main direction of the portal is posting real estate advertisements. It has rich functionality of the user’s personal account, admin panel, payment system, ad personalization and much more.",
            ru: "Большой проект на базе фреймворка Yii2, разработанный командой из трех человек. Основное направление портала - размещение объявлений о недвижимости. Имеет богатый функционал личного кабинета пользователя, админ-панели, системы оплаты, персонализации объявлений и многое другое",
        },
        domain: "Real estate",
        rating: 4.6,
        year: 2019,
        status: "completed",
        participating: "team",
        devTimeMonths: 14,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Yii2", "MySQL"],
        images: 18,
    },
    {
        slug: "webarch-theme",
        name: { en: "WebArchitect WordPress Theme", ru: "Тема WordPress WebArchitect" },
        shortName: { en: "WebArchitect WP Theme", ru: "Тема WP WebArchitect" },
        description: { en: "WebArchitect EN", ru: "WebArchitect RU" },
        domain: "Wordpress",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "React", "PHP", "Wordpress", "MySQL"],
        images: 0,
    },
    {
        slug: "auto-stock",
        name: {
            en: "Website for keeping track of auto parts warehouse balances",
            ru: "Сайт учета остатков склада автозапчастей",
        },
        shortName: { en: "Auto parts warehouse", ru: "Склад автозапчастей" },
        description: { en: "Auto parts warehouse", ru: "Склад автозапчастей" },
        domain: "Retail services",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL", "1C"],
        images: 0,
    },
    {
        slug: "turicum",
        name: { en: "Turicum - insurance company", ru: "Турикум - страховая компания" },
        shortName: { en: "Insurance company", ru: "Страховая компания" },
        description: { en: "Insurance company", ru: "Страховая компания" },
        domain: "Finance",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        images: 0,
    },
    {
        slug: "formula",
        name: { en: "Health Formula - clinic website", ru: "Формула здоровья — сайт клиники" },
        shortName: { en: "Clinic website", ru: "Сайт клиники" },
        description: { en: "Clinic website", ru: "Сайт клиники" },
        domain: "Healthcare",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL"],
        images: 0,
    },
    {
        slug: "hs-portal",
        name: { en: "HS-PORTAL — сonstruction company", ru: "HS-PORTAL — строительная компания" },
        shortName: { en: "Construction company", ru: "Строительная компания" },
        description: { en: "Construction company", ru: "Строительная компания" },
        domain: "Сonstruction",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL"],
        images: 0,
    },
    {
        slug: "numerology",
        name: { en: "2matrix — numerology", ru: "2matrix — нумерология" },
        shortName: { en: "Numerology", ru: "Нумерология" },
        description: {
            en: "The solution based on the Yii2 framework is an online service for providing paid services for individual numerological calculations, compatibility and profession calculations, and «fate and will» graphics.",
            ru: "Решение на базе фреймворка Yii2 представляет собой онлайн сервис оказания платных услуг по индивидуальному нумерологическому расчету, расчету совместимости и профессии, графика «судьбы и воли».",
        },
        domain: "Retail services",
        rating: 4.3,
        year: 2020,
        status: "completed",
        participating: "team",
        devTimeMonths: 3,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Yii2", "MySQL"],
        images: 4,
        coverBrightmess: "dark",
    },
    {
        slug: "krocus",
        name: { en: "Gas station network Crocus", ru: "Сеть АЗС Крокус" },
        shortName: { en: "GSN Crocus", ru: "АЗС Крокус" },
        description: { en: "GSN Crocus", ru: "АЗС Крокус" },
        domain: "Retail services",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        images: 0,
    },
    {
        slug: "wordsense",
        name: {
            en: "WordSense - interactive English textbook",
            ru: "WordSense - интерактивный учебник английского языка",
        },
        shortName: { en: "English textbook", ru: "Учебник английского" },
        description: { en: "English textbook", ru: "Учебник английского" },
        domain: "Education",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        gitHubLink: "https://github.com/miraxsage/wordsense",
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        images: 0,
    },
    {
        slug: "miraxsage",
        name: { en: "Miraxsage - Portfolio website", ru: "Miraxsage - Сайт портфолио" },
        shortName: { en: "Portfolio website", ru: "Сайт портфолио" },
        description: { en: "Portfolio website", ru: "Сайт портфолио" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        images: 0,
        coverBrightmess: "dark",
    },

    //desktop
    {
        slug: "my-squirrel",
        name: {
            en: "MySquirrel - Personal database management system",
            ru: "MySquirrel - Система управления персональными базами данных",
        },
        shortName: { en: "PDMS MySquirrel", ru: "СУПБД MySquirrel" },
        description: { en: "PDMS MySquirrel", ru: "СУПБД MySquirrel" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "syntax-resolver",
        name: { en: "SyntaxResolver - syntax translator", ru: "SyntaxResolver - синтаксический транслятор" },
        shortName: { en: "Syntax translator", ru: "Синтаксический транслятор" },
        description: { en: "Syntax translator", ru: "Синтаксический транслятор" },
        domain: "Research",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "dep-workflow",
        name: {
            en: "DepWorkflow - department document management program",
            ru: "DepWorkflow - программа управления документооборотом отдела",
        },
        shortName: { en: "Document management", ru: "Управление документооборотом" },
        description: { en: "Document management", ru: "Управление документооборотом" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "multi-cropper",
        name: {
            en: "ImageMultiCropper - batch processor for cropping scanned images",
            ru: "ImageMultiCropper - пакетный обработчик обрезки сканированных изображений",
        },
        shortName: { en: "ImageMultiCropper", ru: "ImageMultiCropper" },
        description: { en: "ImageMultiCropper EN", ru: "ImageMultiCropper RU" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
        coverBrightmess: "dark",
    },
    {
        slug: "mutial-imaging",
        name: {
            en: "MutialImaging - batch image processing program",
            ru: "MutialImaging - программа для пакетной обработки изображений",
        },
        shortName: { en: "MutialImaging", ru: "MutialImaging" },
        description: { en: "MutialImaging EN", ru: "MutialImaging RU" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
        coverBrightmess: "dark",
    },
    {
        slug: "key-macros",
        name: { en: "KeyMacros - keystroke emulation macro", ru: "KeyMacros - макрос эмуляции нажатии клавиш" },
        shortName: { en: "KeyMacros", ru: "KeyMacros" },
        description: { en: "KeyMacros EN", ru: "KeyMacros RU" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
        coverBrightmess: "dark",
    },
    {
        slug: "extemal-optimization",
        name: {
            en: "Extreme optimization - multidimensional optimization problems",
            ru: "Экстремальная оптимизация - задачи многомерной оптимизации",
        },
        shortName: { en: "Extreme optimization", ru: "Экстремальная оптимизация" },
        description: { en: "Extreme optimization", ru: "Экстремальная оптимизация" },
        domain: "Research",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "water-marker",
        name: {
            en: "WaterMarker - Batch processor for images and PDF documents",
            ru: "WaterMarker - Пакетный обработчик изображений и PDF-документов",
        },
        shortName: { en: "WaterMarker", ru: "WaterMarker" },
        description: { en: "WaterMarker EN", ru: "WaterMarker RU" },
        domain: "Application solutions",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "gal-extender",
        name: {
            en: "GalExtender - Bot for sending information and advertising messages",
            ru: "GalExtender - Бот рассылки информационных и рекламных сообщений",
        },
        shortName: { en: "GalExtender", ru: "GalExtender" },
        description: { en: "GalExtender EN", ru: "GalExtender RU" },
        domain: "Advertising",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
        coverBrightmess: "dark",
    },
    {
        slug: "mtool",
        name: { en: "MTool - Interactive teacher journal", ru: "MTool - Интерактивный журнал преподавателя" },
        shortName: { en: "Teacher journal", ru: "Журнал преподавателя" },
        description: { en: "Teacher journal", ru: "Журнал преподавателя" },
        domain: "Education",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
    {
        slug: "suzrp",
        name: {
            en: "SUZRP - piecework salary accounting for cable production",
            ru: "СУЗРП - сдельный учет зарплаты кабельного производства",
        },
        shortName: { en: "SUZRP 1C", ru: "СУЗРП 1С" },
        description: { en: "SUZRP 1C", ru: "СУЗРП 1С" },
        domain: "Finance",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: ["1C"],
        images: 0,
    },
    {
        slug: "cook-book",
        name: {
            en: "CookBook - Auto-calculation table for product consumption",
            ru: "CookBook - Таблица авто-расчета расхода продуктов",
        },
        shortName: { en: "CookBook", ru: "CookBook" },
        description: { en: "CookBook EN", ru: "CookBook RU" },
        domain: "Cooking",
        rating: 3.5,
        year: 2018,
        status: "completed",
        participating: "team",
        devTimeMonths: 11,
        technologies: [".NET Framework", "Visual C#", "WPF"],
        images: 0,
    },
] as const satisfies ProjectInterface[];
