import { TechnologiesList } from "../About/Blocks/specs/Technologies";

export type ProjectInterface = {
    slug: string;
    name: string;
    images: string[];
    technologies: TechnologiesList[];
    rating: number;
    status: "developing" | "completed";
    description: string;
    coverBrightmess?: "ligth" | "dark";
    content: string;
};

export const projects: ProjectInterface[] = [
    //web
    {
        slug: "kvll",
        name: "Портал строительной недвижимости Краснодара",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Yii2"],
        rating: 3.5,
        status: "completed",
        description: "123",
        content: "321",
    },
    {
        slug: "webarch-theme",
        name: "Тема WordPress WebArchitect",
        images: [],
        technologies: ["HTML", "CSS", "JS", "React", "PHP", "Wordpress", "MySQL"],
        rating: 4.3,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "auto-stock",
        name: "Сайт учета остатков склада автозапчастей",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL", "1C"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "turicum",
        name: "Турикум - страховая компания",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "formula",
        name: "Формула здоровья — сайт клиники",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "hs-portal",
        name: "HS-PORTAL — строительная компания",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress", "MySQL"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "numerology",
        name: "2matrix — нумерология",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },
    {
        slug: "krocus",
        name: "Сеть АЗС Крокус",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "wordsense",
        name: "WordSense - интерактивный учебник английского языка",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "miraxsage",
        name: "Miraxsage - Сайт портфолио",
        images: [],
        technologies: ["HTML", "CSS", "JS", "JQuery", "PHP", "Wordpress"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },

    //desktop
    {
        slug: "my-squirrel",
        name: "MySquirrel - Система управления персональными базами данных",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "syntax-resolver",
        name: "SyntaxResolver - синтаксический транслятор",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "dep-workflow",
        name: "DepWorkflow - программа управления документооборотом отдела",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "multi-cropper",
        name: "ImageMultiCropper - пакетный обработчик обрезки сканированных изображений",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },
    {
        slug: "mutial-imaging",
        name: "MutialImaging - программа для пакетной обработки изображений",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },
    {
        slug: "key-macros",
        name: "KeyMacros - макрос эмуляции нажатии клавиш",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },
    {
        slug: "extemal-optimization",
        name: "Экстремальная оптимизация - задачи многомерной оптимизации",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "water-marker",
        name: "WaterMarker - Пакетный обработчик изображений и PDF-документов",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "gal-extender",
        name: "GalExtender - Бот рассылки информационных и рекламных сообщений",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
        coverBrightmess: "dark",
    },
    {
        slug: "mtool",
        name: "MTool - Интерактивный журнал преподавателя",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "suzrp",
        name: "СУЗРП - сдельный учет зарплаты кабельного производства",
        images: [],
        technologies: ["1C"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
    {
        slug: "cook-book",
        name: "CookBook - Таблица авто-расчета расхода продуктов",
        images: [],
        technologies: [".NET Framework", "Visual C#", "WPF"],
        rating: 3.5,
        status: "completed",
        description: "345",
        content: "543",
    },
];
